### ISSUE TITLE
Guidance on plugin names

### ISSUE THREAD

**Issue by jonathantneal** [himynameisdave/postcss-plugins#162]
For the plugin name, do you want the npm name or a common name or what? For instance, almost all of my plugins start with `postcss-`, but a plugin name itself might be "Time Machine" with uppercases and a space.

**Comment by himynameisdave** [comment]
The plugin name can be anything, it doesn't have to match the npm name or the name of the Github URL. But when adding a plugin that doesn't start with `"postcss-"` [you will get a warning](https://github.com/himynameisdave/postcss-plugins/blob/master/scripts/data/newPluginPrompts.js#L19-L21) just letting you know that most plugins use that prefix to make them easier to find.

**Comment by himynameisdave** [comment]
Closing as I feel like the [warning I mentioned above ☝️ ](https://github.com/himynameisdave/postcss-plugins/issues/162#issuecomment-263682411) should be enough for guidance on naming.
