### ISSUE TITLE
Alfred Workflow

### ISSUE THREAD

**Issue by chrisopedia** [himynameisdave/postcss-plugins#20]
I created an [Alfred Workflow](https://github.com/chrisopedia/alfred-postcss-workflow) based off your site. If you use Alfred, go check it out, and let me know what you think.  Keep up the great work!!!

**Comment by ben-eb** [comment]
@chrisopedia Thanks, awesome work! I will promote this on our PostCSS twitter account. :+1:

**Comment by chrisopedia** [comment]
@ben-eb, saw that this morning.  Thanks so much for that.

**Comment by ben-eb** [comment]
No problem. :smile:

**Comment by himynameisdave** [comment]
Very cool, I've spent the last few days investigating what Alfred even was :+1:

**Comment by himynameisdave** [comment]
Closing this now
