### ISSUE TITLE
opening a page in a new tab results in a 404

### ISSUE THREAD

**Issue by sturobson** [himynameisdave/postcss-plugins#223]
If I right-click on one of the tiles to open in a new tab I would presume the page would load in a new tab.

https://www.postcss.parts/tag/fun

expected behaviour: If I right-click a tile, like 'fun', I would expect the page to load.

actual behaviour: page does not load.

**Comment by himynameisdave** [comment]
This is not the correct repository for this issue, please report to this repo instead:

https://github.com/mxstbr/postcss.parts
