### ISSUE TITLE
pre-commit hook failed 

### ISSUE THREAD

**Issue by retyui** [himynameisdave/postcss-plugins#232]
I try to add new plugin, but:
```
Authors list sucessfully updated in only: 9.067ms

/postcss-plugins/scripts/utils/fetchGithubStars.js
  2:27  error  Unable to resolve path to module '../../token.json'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)
```

**Comment by himynameisdave** [comment]
This is expected, and would happen if you were trying to run `npm run update-stars`, because it needs a GitHub token. This is generally only run by maintainers when we do version bumps.

---

If you would like to add a plugin, please run `npm run add`, which will not require a token to complete.

**Comment by retyui** [comment]
Really? You think I'm so stupid?
That I have not read readme?
Remove this [line](https://github.com/himynameisdave/postcss-plugins/blob/master/package.json#L18) it prevents commits to users!!!

**Comment by himynameisdave** [comment]
@retyui Nope, I don't think that you are at all.

I will reopen this issue and take another look, perhaps one of the tests is looking for a token that is not there. 

Thank you for reporting, I appreciate it.

**Comment by himynameisdave** [comment]
Removed the problematic test case in 0a4d657c4be488b9e128ab424ac70a4f0d3ccf1b, will look at replacing it later.

Should be good as of `v1.11.0`. Thank you for reporting!

**Comment by philipbordallo** [comment]
@himynameisdave ran into this issue as well when trying to `git push` to my fork so I could add a plugin, using `--no-verify` solved it, but that seems like a temporary fix.

It begs the question: does it make sense to have a static count of github stars for each plugin that will only be accurate when someone git pushes?
