### ISSUE TITLE
authors.md is dead

### ISSUE THREAD

**Issue by jonathantneal** [himynameisdave/postcss-plugins#56]
It’s currently dead. https://github.com/himynameisdave/postcss-plugins/blob/master/docs/authors.md

This commit killed it. https://github.com/himynameisdave/postcss-plugins/commit/b82337afaebbcc43fb69815c46f4259a215f8e00#diff-365b0403c12f88b9d3bbdfb3f3b077a4

**Comment by himynameisdave** [comment]
@jonathantneal thanks, fixed now!
